### ISSUE TITLE
Update packagist

### ISSUE THREAD

**Issue by alanrodas** [josegonzalez/cakephp-entity#14]
Hello there,

I see in the repo that there were many releases (3.0.0 being the latest) since 1.0.0 and I was wondering if packagist could be updated accordingly. I would like to freeze the version of the library to a specific one and not be tied to a dev-master branch just in case of anything changes in the future.

Is there any chance this could be done??

**Comment by josegonzalez** [comment]
Fixed. Was an issue with the composer.json including a version attribute that was incorrect. Thanks for opening the issue!
