### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by garethellis36** [josegonzalez/cakephp-entity#15]
Hello!

The headline on this repo home page says:
`CakePHP2: Deprecated Table/Entity wrapper around old Model system`

Is it "deprecated" because something else for Cake 2 has replaced this? Or because Cake3 is out?

**Comment by josegonzalez** [comment]
Because cake3 is out. "Not actively maintained" would be better I guess.

**Comment by sebastienbarre** [comment]
Thanks for clarifying. There are still people using 2.x, trying to find tools to ease the transition to 3.x. We will give a shot to this plugin, maybe it will make it easier to convert to 3.x's Table and Entity later on...

**Comment by josegonzalez** [comment]
@sebastienbarre if you have proposals for making this repository map more closely to Cake 3's ORM, I'm happy to pull them in.
